export const CATEGORIES = [
  {
    id: 'cat-1',
    name: 'Dogs',
    slug: 'dogs',
    description: 'Everything for your canine companion',
    productCount: 8,
  },
  {
    id: 'cat-2',
    name: 'Cats',
    slug: 'cats',
    description: 'Premium products for feline friends',
    productCount: 7,
  },
  {
    id: 'cat-3',
    name: 'Birds',
    slug: 'birds',
    description: 'Food and accessories for birds',
    productCount: 5,
  },
  {
    id: 'cat-4',
    name: 'Fish',
    slug: 'fish',
    description: 'Aquarium supplies and fish food',
    productCount: 5,
  },
  {
    id: 'cat-5',
    name: 'Small Animals',
    slug: 'small-animals',
    description: 'Products for small furry friends',
    productCount: 5,
  },
];

export const PRODUCTS = [
  // Dogs
  {
    id: 'prod-1',
    name: 'Royal Canin Maxi Adult',
    description:
      'Complete and balanced dry food designed for large breed adult dogs (26–44 kg) over 15 months old. Adapted kibble shape and texture for large breeds, with a precise balance of nutrients to support healthy muscle mass and an ideal weight.',
    price: 52.99,
    image: 'https://picsum.photos/seed/rc-maxi-adult/600/600',
    category: 'dogs',
    subcategory: 'food',
    featured: true,
    bestseller: true,
    newArrival: false,
    stock: 45,
  },
  {
    id: 'prod-2',
    name: 'Purina Pro Plan Puppy',
    description:
      'High-quality puppy food with real chicken as the first ingredient. Supports healthy development during the first year of life with DHA from omega-rich fish oil. No artificial colors or flavors added.',
    price: 45.99,
    image: 'https://picsum.photos/seed/purina-puppy/600/600',
    category: 'dogs',
    subcategory: 'food',
    featured: true,
    bestseller: false,
    newArrival: false,
    stock: 32,
  },
  {
    id: 'prod-3',
    name: 'Kong Classic Dog Toy',
    description:
      'Durable natural red rubber toy designed for average chewers. Bounce for a game of fetch and stuff with treats for extended entertainment. Cleans teeth and gums and satisfies natural chewing instincts.',
    price: 14.99,
    image: 'https://picsum.photos/seed/kong-classic/600/600',
    category: 'dogs',
    subcategory: 'toys',
    featured: false,
    bestseller: true,
    newArrival: false,
    stock: 78,
  },
  {
    id: 'prod-4',
    name: 'Ruffwear Front Range Harness',
    description:
      'Everyday dog harness with padded chest and belly panels for all-day comfort. Features two leash attachment points — a front ring for training and a back ring for everyday walking.',
    price: 79.99,
    image: 'https://picsum.photos/seed/ruffwear-harness/600/600',
    category: 'dogs',
    subcategory: 'accessories',
    featured: false,
    bestseller: false,
    newArrival: false,
    stock: 23,
  },
  {
    id: 'prod-5',
    name: 'Benebone Wishbone Chew Toy',
    description:
      'Made in the USA with real bacon flavor baked in — not a surface coating. Ergonomic design makes it easy for dogs to grip and chew independently. For aggressive chewers.',
    price: 19.99,
    image: 'https://picsum.photos/seed/benebone-wishbone/600/600',
    category: 'dogs',
    subcategory: 'toys',
    featured: false,
    bestseller: true,
    newArrival: false,
    stock: 56,
  },
  {
    id: 'prod-6',
    name: 'Blue Buffalo Life Protection',
    description:
      'Natural dog food with real chicken and wholesome grains. No chicken by-product meals, no corn, wheat, or soy. LifeSource Bits provide a precise blend of antioxidants, vitamins and minerals.',
    price: 48.99,
    image: 'https://picsum.photos/seed/blue-buffalo/600/600',
    category: 'dogs',
    subcategory: 'food',
    featured: false,
    bestseller: false,
    newArrival: false,
    stock: 29,
  },
  {
    id: 'prod-7',
    name: 'Outward Hound Hide-a-Squirrel',
    description:
      'Award-winning plush puzzle toy. Dogs hunt for squeaky stuffed squirrels hidden inside a tree trunk. Satisfies natural hunting instincts while providing mental stimulation and play.',
    price: 12.99,
    image: 'https://picsum.photos/seed/hide-squirrel/600/600',
    category: 'dogs',
    subcategory: 'toys',
    featured: false,
    bestseller: false,
    newArrival: true,
    stock: 44,
  },
  {
    id: 'prod-8',
    name: 'Nulo Adult Grain-Free Dry Food',
    description:
      'High-meat content with real turkey as the first ingredient. Grain-free recipe with low glycemic index ingredients to support healthy weight management. Includes BC30 probiotic for digestive health.',
    price: 55.99,
    image: 'https://picsum.photos/seed/nulo-adult/600/600',
    category: 'dogs',
    subcategory: 'food',
    featured: false,
    bestseller: false,
    newArrival: true,
    stock: 18,
  },

  // Cats
  {
    id: 'prod-9',
    name: 'Royal Canin Indoor Adult',
    description:
      'Formulated specifically for adult cats living exclusively indoors. Helps maintain a healthy weight, reduces hairball formation, and controls litter box odor. Complete and balanced nutrition.',
    price: 38.99,
    image: 'https://picsum.photos/seed/rc-indoor-cat/600/600',
    category: 'cats',
    subcategory: 'food',
    featured: true,
    bestseller: true,
    newArrival: false,
    stock: 52,
  },
  {
    id: 'prod-10',
    name: 'Whiskas Wet Food Variety Pack',
    description:
      'Twelve pouches with a mix of meaty favorites in jelly and sauce. 100% complete and balanced nutrition to help keep adult cats healthy, happy, and satisfied throughout the day.',
    price: 18.99,
    image: 'https://picsum.photos/seed/whiskas-wet/600/600',
    category: 'cats',
    subcategory: 'food',
    featured: false,
    bestseller: false,
    newArrival: false,
    stock: 63,
  },
  {
    id: 'prod-11',
    name: 'PetFusion Ultimate Cat Scratcher',
    description:
      'Award-winning reversible scratcher lounge in recycled cardboard. Modern design doubles as a comfortable nap spot. Cats love the texture and the lounge curve — it encourages natural scratching behavior.',
    price: 44.99,
    image: 'https://picsum.photos/seed/petfusion-scratcher/600/600',
    category: 'cats',
    subcategory: 'accessories',
    featured: false,
    bestseller: true,
    newArrival: false,
    stock: 31,
  },
  {
    id: 'prod-12',
    name: 'Catit Flower Fountain',
    description:
      'Encourages cats to drink more water with a flower-shaped stream. Three different water flow settings to match each cat\'s preference. 3-liter capacity with triple-action water softening filter.',
    price: 34.99,
    image: 'https://picsum.photos/seed/catit-fountain/600/600',
    category: 'cats',
    subcategory: 'accessories',
    featured: true,
    bestseller: false,
    newArrival: false,
    stock: 27,
  },
  {
    id: 'prod-13',
    name: 'Da Bird Feather Teaser Wand',
    description:
      'The original bestselling cat wand toy. Unique feathers create a realistic bird sound when swooshed through air. Triggers natural hunting instincts and provides excellent exercise for indoor cats.',
    price: 9.99,
    image: 'https://picsum.photos/seed/dabird-wand/600/600',
    category: 'cats',
    subcategory: 'toys',
    featured: false,
    bestseller: false,
    newArrival: false,
    stock: 89,
  },
  {
    id: 'prod-14',
    name: 'Orijen Cat & Kitten Formula',
    description:
      'Biologically appropriate cat food with 90% quality animal ingredients. Free-run chicken and turkey, nest-laid eggs, and wild-caught fish provide complete and balanced nutrition. Grain-free, freeze-dried coated.',
    price: 64.99,
    image: 'https://picsum.photos/seed/orijen-cat/600/600',
    category: 'cats',
    subcategory: 'food',
    featured: false,
    bestseller: false,
    newArrival: true,
    stock: 15,
  },
  {
    id: 'prod-15',
    name: 'SmartCat Pioneer Pet Scratcher',
    description:
      'Satisfies cats natural urge to scratch with natural sisal. Adjustable height works for cats of all sizes. Sturdy base prevents tipping. Double-sided design extends the product life.',
    price: 24.99,
    image: 'https://picsum.photos/seed/smartcat-sisal/600/600',
    category: 'cats',
    subcategory: 'accessories',
    featured: false,
    bestseller: false,
    newArrival: true,
    stock: 38,
  },

  // Birds
  {
    id: 'prod-16',
    name: 'Versele-Laga Prestige Parakeet',
    description:
      'Premium seed mix for parakeets and budgerigars. A blend of high-quality grains and seeds with millet sprays. Highly palatable and nutritionally balanced for optimal health and vibrant plumage.',
    price: 22.99,
    image: 'https://picsum.photos/seed/versele-parakeet/600/600',
    category: 'birds',
    subcategory: 'food',
    featured: true,
    bestseller: false,
    newArrival: false,
    stock: 42,
  },
  {
    id: 'prod-17',
    name: 'Penn Plax Bird Flight Cage',
    description:
      'Spacious flight cage perfect for parakeets, cockatiels, and finches. Includes 4 plastic perches, 4 feeding cups, and a removable bottom tray. Durable powder-coated wire for long-lasting use.',
    price: 89.99,
    image: 'https://picsum.photos/seed/penn-birdcage/600/600',
    category: 'birds',
    subcategory: 'accessories',
    featured: false,
    bestseller: false,
    newArrival: false,
    stock: 12,
  },
  {
    id: 'prod-18',
    name: 'HARI Smart Pellets for Parakeets',
    description:
      'Nutritionally complete and balanced pellets formulated specifically for parakeets. Made with natural ingredients without artificial colors or preservatives. Supports healthy feathers and vibrant colors.',
    price: 29.99,
    image: 'https://picsum.photos/seed/hari-pellets/600/600',
    category: 'birds',
    subcategory: 'food',
    featured: false,
    bestseller: false,
    newArrival: true,
    stock: 28,
  },
  {
    id: 'prod-19',
    name: 'JW Pet ActiviToy Disco Ball',
    description:
      'Colorful bird toy with a shiny metallic disco ball center and hanging strands. Inspires exercise and play. Attaches easily to any cage. Suitable for parakeets, cockatiels, and similarly sized birds.',
    price: 7.99,
    image: 'https://picsum.photos/seed/jw-disco-toy/600/600',
    category: 'birds',
    subcategory: 'toys',
    featured: false,
    bestseller: false,
    newArrival: false,
    stock: 67,
  },
  {
    id: 'prod-20',
    name: 'Prevue Hendryx Playpen Bird Gym',
    description:
      'Freestanding bird gym play stand with hardwood perches, stainless steel cups, and hanging toys. Encourages healthy activity and socialization outside the cage. Easy to assemble and clean.',
    price: 59.99,
    image: 'https://picsum.photos/seed/prevue-gym/600/600',
    category: 'birds',
    subcategory: 'accessories',
    featured: false,
    bestseller: false,
    newArrival: false,
    stock: 9,
  },

  // Fish
  {
    id: 'prod-21',
    name: 'Tetra Goldfish Flakes',
    description:
      'Complete and balanced food for all goldfish. Floating flakes prevent overfeeding and maintain clear water. Enhanced with ProCare blend to support the immune system and promote long-term health.',
    price: 8.99,
    image: 'https://picsum.photos/seed/tetra-goldfish/600/600',
    category: 'fish',
    subcategory: 'food',
    featured: true,
    bestseller: true,
    newArrival: false,
    stock: 92,
  },
  {
    id: 'prod-22',
    name: 'API Freshwater Master Test Kit',
    description:
      'Tests the most important aquarium water parameters to avoid fish stress. Includes over 800 tests for pH, Ammonia, Nitrite, and Nitrate. Color-coded instruction card makes reading results simple.',
    price: 29.99,
    image: 'https://picsum.photos/seed/api-testkit/600/600',
    category: 'fish',
    subcategory: 'accessories',
    featured: false,
    bestseller: true,
    newArrival: false,
    stock: 55,
  },
  {
    id: 'prod-23',
    name: 'Fluval Flex 57L Aquarium Kit',
    description:
      'Fully curved front panel with a powerful multi-color LED light system and quiet multi-stage filter. Complete starter kit for a beautiful freshwater aquarium. Includes remote control for lighting.',
    price: 149.99,
    image: 'https://picsum.photos/seed/fluval-flex/600/600',
    category: 'fish',
    subcategory: 'accessories',
    featured: false,
    bestseller: false,
    newArrival: true,
    stock: 7,
  },
  {
    id: 'prod-24',
    name: 'Hikari Cichlid Gold Pellets',
    description:
      'Color-enhancing cichlid food in mini pellet form. Developed to promote the natural beauty of your fish. Highly digestible ingredients reduce waste and maintain clear water quality.',
    price: 12.99,
    image: 'https://picsum.photos/seed/hikari-cichlid/600/600',
    category: 'fish',
    subcategory: 'food',
    featured: false,
    bestseller: false,
    newArrival: false,
    stock: 43,
  },
  {
    id: 'prod-25',
    name: 'Marina 60 Aquarium Starter Kit',
    description:
      'Complete aquarium starter kit for a 60-liter tank. Includes Marina Slim Filter, Aqua-Glo light, fish net, thermometer, and biological supplement. The perfect kit for first-time aquarium owners.',
    price: 74.99,
    image: 'https://picsum.photos/seed/marina-60/600/600',
    category: 'fish',
    subcategory: 'accessories',
    featured: false,
    bestseller: false,
    newArrival: false,
    stock: 14,
  },

  // Small Animals
  {
    id: 'prod-26',
    name: 'Kaytee Natural Timothy Hay',
    description:
      'Premium quality first cut timothy hay for rabbits, guinea pigs, and chinchillas. High in fiber to support healthy digestive function. Fresh picked and sun-cured for maximum nutritional value.',
    price: 14.99,
    image: 'https://picsum.photos/seed/kaytee-hay/600/600',
    category: 'small-animals',
    subcategory: 'food',
    featured: true,
    bestseller: false,
    newArrival: false,
    stock: 68,
  },
  {
    id: 'prod-27',
    name: 'Vitakraft Hamster Emotion Mix',
    description:
      'Species-appropriate feed for hamsters. Contains high-quality grain varieties, dried vegetables, and protein-rich components. Nutritionally balanced for complete daily nourishment.',
    price: 9.99,
    image: 'https://picsum.photos/seed/vitakraft-hamster/600/600',
    category: 'small-animals',
    subcategory: 'food',
    featured: false,
    bestseller: true,
    newArrival: false,
    stock: 74,
  },
  {
    id: 'prod-28',
    name: 'Living World Deluxe Habitat',
    description:
      'Premium small animal habitat with wire upper frame and deep plastic base. Includes balcony with access ramp, feeding bowl, water bottle, hay guard, and a hideout for rest and privacy.',
    price: 89.99,
    image: 'https://picsum.photos/seed/living-world-habitat/600/600',
    category: 'small-animals',
    subcategory: 'accessories',
    featured: false,
    bestseller: false,
    newArrival: true,
    stock: 11,
  },
  {
    id: 'prod-29',
    name: 'Oxbow Garden Select Hamster Food',
    description:
      'Thoughtfully formulated with premium botanicals, herbs, and vegetables. Made without added sugars, artificial preservatives, or colors. A wholesome daily diet for hamsters and gerbils.',
    price: 11.99,
    image: 'https://picsum.photos/seed/oxbow-hamster/600/600',
    category: 'small-animals',
    subcategory: 'food',
    featured: false,
    bestseller: false,
    newArrival: false,
    stock: 36,
  },
  {
    id: 'prod-30',
    name: 'Niteangel Wooden Hamster Wheel',
    description:
      'Super-silent spinner wheel with smooth-running ball bearings. Natural solid wood construction is safe for hamsters and all small pets. Easy to assemble and detach for cleaning.',
    price: 24.99,
    image: 'https://picsum.photos/seed/niteangel-wheel/600/600',
    category: 'small-animals',
    subcategory: 'toys',
    featured: false,
    bestseller: false,
    newArrival: true,
    stock: 22,
  },
];

function toSlug(name) {
  return name
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim();
}

PRODUCTS.forEach((p) => {
  p.slug = toSlug(p.name);
});
