export const CATEGORIES = [
  {
    id: 'cat-1',
    name: 'Câini',
    slug: 'dogs',
    description: 'Tot ce are nevoie câinele tău',
    productCount: 8,
  },
  {
    id: 'cat-2',
    name: 'Pisici',
    slug: 'cats',
    description: 'Produse premium pentru feline',
    productCount: 7,
  },
  {
    id: 'cat-3',
    name: 'Păsări',
    slug: 'birds',
    description: 'Hrană și accesorii pentru păsări',
    productCount: 5,
  },
  {
    id: 'cat-4',
    name: 'Pești',
    slug: 'fish',
    description: 'Echipamente și hrană pentru acvarii',
    productCount: 5,
  },
  {
    id: 'cat-5',
    name: 'Animale Mici',
    slug: 'small-animals',
    description: 'Produse pentru animale mici',
    productCount: 5,
  },
];

export const PRODUCTS = [
  // Câini
  {
    id: 'prod-1',
    name: 'Royal Canin Maxi Adult',
    description:
      'Hrană uscată completă și echilibrată, special concepută pentru câinii de rasă mare adulți (26–44 kg), cu vârsta de peste 15 luni. Kibble adaptat ca formă și textură, cu o balanță precisă de nutrienți pentru menținerea masei musculare și a greutății ideale.',
    price: 499,
    image: 'https://picsum.photos/seed/rc-maxi-adult/600/600',
    category: 'dogs',
    subcategory: 'food',
    featured: true,
    bestseller: true,
    newArrival: false,
    stock: 45,
  },
  {
    id: 'prod-2',
    name: 'Purina Pro Plan Puppy',
    description:
      'Hrană de calitate superioară pentru căței cu pui real ca prim ingredient. Sprijină dezvoltarea sănătoasă în primul an de viață cu DHA din ulei de pește bogat în omega-3. Fără coloranți sau arome artificiale.',
    price: 429,
    image: 'https://picsum.photos/seed/purina-puppy/600/600',
    category: 'dogs',
    subcategory: 'food',
    featured: true,
    bestseller: false,
    newArrival: false,
    stock: 32,
  },
  {
    id: 'prod-3',
    name: 'Kong Classic Dog Toy',
    description:
      'Jucărie durabilă din cauciuc natural roșu, pentru câini cu obiceiul de a mesteca. Poate fi umplută cu recompense pentru distracție prelungită. Curăță dinții și gingiile și satisface instinctele naturale de mestecare.',
    price: 149,
    image: 'https://picsum.photos/seed/kong-classic/600/600',
    category: 'dogs',
    subcategory: 'toys',
    featured: false,
    bestseller: true,
    newArrival: false,
    stock: 78,
  },
  {
    id: 'prod-4',
    name: 'Ruffwear Front Range Harness',
    description:
      'Ham pentru câini pentru uz zilnic cu panouri moi căptușite pe piept și burtă, pentru confort pe toată ziua. Două puncte de atașare pentru lesă — inel frontal pentru dresaj și inel dorsal pentru plimbări zilnice.',
    price: 749,
    image: 'https://picsum.photos/seed/ruffwear-harness/600/600',
    category: 'dogs',
    subcategory: 'accessories',
    featured: false,
    bestseller: false,
    newArrival: false,
    stock: 23,
  },
  {
    id: 'prod-5',
    name: 'Benebone Wishbone Chew Toy',
    description:
      'Fabricat în SUA cu aromă reală de bacon integrată, nu doar pe suprafață. Design ergonomic care permite câinilor să mestece independent. Ideal pentru câini cu obiceiul agresiv de mestecare.',
    price: 199,
    image: 'https://picsum.photos/seed/benebone-wishbone/600/600',
    category: 'dogs',
    subcategory: 'toys',
    featured: false,
    bestseller: true,
    newArrival: false,
    stock: 56,
  },
  {
    id: 'prod-6',
    name: 'Blue Buffalo Life Protection',
    description:
      'Hrană naturală pentru câini cu pui adevărat și cereale sănătoase. Fără subproduse din pui, porumb, grâu sau soia. Biți LifeSource oferă o combinație precisă de antioxidanți, vitamine și minerale.',
    price: 459,
    image: 'https://picsum.photos/seed/blue-buffalo/600/600',
    category: 'dogs',
    subcategory: 'food',
    featured: false,
    bestseller: false,
    newArrival: false,
    stock: 29,
  },
  {
    id: 'prod-7',
    name: 'Outward Hound Hide-a-Squirrel',
    description:
      'Jucărie puzzle din pluș premiată. Câinii vânează veverițe cu sunet, ascunse într-un trunchi de copac. Satisface instinctele naturale de vânătoare și oferă stimulare mentală excelentă.',
    price: 129,
    image: 'https://picsum.photos/seed/hide-squirrel/600/600',
    category: 'dogs',
    subcategory: 'toys',
    featured: false,
    bestseller: false,
    newArrival: true,
    stock: 44,
  },
  {
    id: 'prod-8',
    name: 'Nulo Adult Grain-Free Dry Food',
    description:
      'Conținut ridicat de carne cu curcan real ca prim ingredient. Rețetă fără cereale cu ingrediente cu indice glicemic scăzut, pentru menținerea greutății sănătoase. Include probiotic BC30 pentru sănătatea digestivă.',
    price: 529,
    image: 'https://picsum.photos/seed/nulo-adult/600/600',
    category: 'dogs',
    subcategory: 'food',
    featured: false,
    bestseller: false,
    newArrival: true,
    stock: 18,
  },

  // Pisici
  {
    id: 'prod-9',
    name: 'Royal Canin Indoor Adult',
    description:
      'Formulat special pentru pisicile adulte care trăiesc exclusiv în interior. Ajută la menținerea greutății optime, reduce formarea ghemotoacelor de păr și controlează mirosul de la litieră. Nutriție completă și echilibrată.',
    price: 369,
    image: 'https://picsum.photos/seed/rc-indoor-cat/600/600',
    category: 'cats',
    subcategory: 'food',
    featured: true,
    bestseller: true,
    newArrival: false,
    stock: 52,
  },
  {
    id: 'prod-10',
    name: 'Whiskas Wet Food Variety Pack',
    description:
      'Douăsprezece pungi cu o combinație de gusturi cu carne în jeleu și sos. Nutriție 100% completă și echilibrată pentru a menține pisicile adulte sănătoase, fericite și satisfăcute pe tot parcursul zilei.',
    price: 179,
    image: 'https://picsum.photos/seed/whiskas-wet/600/600',
    category: 'cats',
    subcategory: 'food',
    featured: false,
    bestseller: false,
    newArrival: false,
    stock: 63,
  },
  {
    id: 'prod-11',
    name: 'PetFusion Ultimate Cat Scratcher',
    description:
      'Zgârietoare-pat reversibilă premiată, din carton reciclat. Design modern care dublează ca loc confortabil de somn. Pisicilor le place textura și curba acestui produs — încurajează comportamentul natural de zgâriere.',
    price: 429,
    image: 'https://picsum.photos/seed/petfusion-scratcher/600/600',
    category: 'cats',
    subcategory: 'accessories',
    featured: false,
    bestseller: true,
    newArrival: false,
    stock: 31,
  },
  {
    id: 'prod-12',
    name: 'Catit Flower Fountain',
    description:
      'Încurajează pisicile să bea mai multă apă cu un jet în formă de floare. Trei setări diferite de curgere pentru preferințele fiecărei pisici. Capacitate de 3 litri cu filtru cu acțiune triplă.',
    price: 329,
    image: 'https://picsum.photos/seed/catit-fountain/600/600',
    category: 'cats',
    subcategory: 'accessories',
    featured: true,
    bestseller: false,
    newArrival: false,
    stock: 27,
  },
  {
    id: 'prod-13',
    name: 'Da Bird Feather Teaser Wand',
    description:
      'Cea mai vândută jucărie cu baghetă pentru pisici. Penele unice creează sunete realiste de pasăre când sunt mișcate prin aer. Declanșează instinctele naturale de vânătoare și oferă exercițiu excelent.',
    price: 99,
    image: 'https://picsum.photos/seed/dabird-wand/600/600',
    category: 'cats',
    subcategory: 'toys',
    featured: false,
    bestseller: false,
    newArrival: false,
    stock: 89,
  },
  {
    id: 'prod-14',
    name: 'Orijen Cat & Kitten Formula',
    description:
      'Hrană biologic adecvată cu 90% ingrediente de calitate din carne. Pui și curcan crescuți liber, ouă proaspete și pește prins din sălbăticie. Fără cereale, acoperit cu ingrediente liofilizate.',
    price: 599,
    image: 'https://picsum.photos/seed/orijen-cat/600/600',
    category: 'cats',
    subcategory: 'food',
    featured: false,
    bestseller: false,
    newArrival: true,
    stock: 15,
  },
  {
    id: 'prod-15',
    name: 'SmartCat Pioneer Pet Scratcher',
    description:
      'Satisface impulsul natural al pisicilor de a zgâria cu sisal natural. Înălțimea ajustabilă se potrivește pisicilor de orice dimensiune. Baza solidă previne răsturnarea. Design reversibil extinde durata de viață.',
    price: 239,
    image: 'https://picsum.photos/seed/smartcat-sisal/600/600',
    category: 'cats',
    subcategory: 'accessories',
    featured: false,
    bestseller: false,
    newArrival: true,
    stock: 38,
  },

  // Păsări
  {
    id: 'prod-16',
    name: 'Versele-Laga Prestige Parakeet',
    description:
      'Amestec premium de semințe pentru perușii și budgerigari. Un amestec de cereale și semințe de înaltă calitate cu spice de mei. Foarte gustos și echilibrat nutrițional pentru penaj viu și sănătos.',
    price: 219,
    image: 'https://picsum.photos/seed/versele-parakeet/600/600',
    category: 'birds',
    subcategory: 'food',
    featured: true,
    bestseller: false,
    newArrival: false,
    stock: 42,
  },
  {
    id: 'prod-17',
    name: 'Penn Plax Bird Flight Cage',
    description:
      'Cușcă spațioasă potrivită pentru perușui, nimfe și finzi. Include 4 cotețe din plastic, 4 căni de hrănire și un tăvi inferior detașabil. Sârmă acoperită cu pudră durabilă pentru utilizare îndelungată.',
    price: 849,
    image: 'https://picsum.photos/seed/penn-birdcage/600/600',
    category: 'birds',
    subcategory: 'accessories',
    featured: false,
    bestseller: false,
    newArrival: false,
    stock: 12,
  },
  {
    id: 'prod-18',
    name: 'HARI Smart Pellets for Parakeets',
    description:
      'Pelete complete și echilibrate nutrițional, formulate specific pentru perușui. Fabricate cu ingrediente naturale fără coloranți sau conservanți artificiali. Susține penaj sănătos și culori vii.',
    price: 289,
    image: 'https://picsum.photos/seed/hari-pellets/600/600',
    category: 'birds',
    subcategory: 'food',
    featured: false,
    bestseller: false,
    newArrival: true,
    stock: 28,
  },
  {
    id: 'prod-19',
    name: 'JW Pet ActiviToy Disco Ball',
    description:
      'Jucărie colorată pentru păsări cu centru de disco ball metalic strălucitor și șnururi agățate. Inspiră exercițiu și joacă. Se atașează ușor la orice cușcă. Potrivit pentru perușui și păsări de dimensiuni similare.',
    price: 79,
    image: 'https://picsum.photos/seed/jw-disco-toy/600/600',
    category: 'birds',
    subcategory: 'toys',
    featured: false,
    bestseller: false,
    newArrival: false,
    stock: 67,
  },
  {
    id: 'prod-20',
    name: 'Prevue Hendryx Playpen Bird Gym',
    description:
      'Stativ de joacă liber stând pentru păsări, cu cotețe din lemn de esență tare, căni din oțel inoxidabil și jucării suspendate. Încurajează activitatea sănătoasă și socializarea în afara cuștii.',
    price: 569,
    image: 'https://picsum.photos/seed/prevue-gym/600/600',
    category: 'birds',
    subcategory: 'accessories',
    featured: false,
    bestseller: false,
    newArrival: false,
    stock: 9,
  },

  // Pești
  {
    id: 'prod-21',
    name: 'Tetra Goldfish Flakes',
    description:
      'Hrană completă și echilibrată pentru toți peștii aurii. Fulgi plutitori previn supraalimentarea și mențin apa curată. Îmbogățit cu formula ProCare pentru susținerea sistemului imunitar și sănătatea pe termen lung.',
    price: 89,
    image: 'https://picsum.photos/seed/tetra-goldfish/600/600',
    category: 'fish',
    subcategory: 'food',
    featured: true,
    bestseller: true,
    newArrival: false,
    stock: 92,
  },
  {
    id: 'prod-22',
    name: 'API Freshwater Master Test Kit',
    description:
      'Testează cei mai importanți parametri ai acvariului pentru a evita stresul peștilor. Include peste 800 de teste: pH, Amoniac, Nitrit și Nitrat. Card de instrucțiuni color-codat pentru citire ușoară.',
    price: 289,
    image: 'https://picsum.photos/seed/api-testkit/600/600',
    category: 'fish',
    subcategory: 'accessories',
    featured: false,
    bestseller: true,
    newArrival: false,
    stock: 55,
  },
  {
    id: 'prod-23',
    name: 'Fluval Flex 57L Aquarium Kit',
    description:
      'Panou frontal complet curbat cu sistem de iluminat LED multi-color puternic și filtru silențios cu mai multe etape. Kit complet pentru un acvariu de apă dulce spectaculos. Include telecomandă pentru iluminat.',
    price: 1399,
    image: 'https://picsum.photos/seed/fluval-flex/600/600',
    category: 'fish',
    subcategory: 'accessories',
    featured: false,
    bestseller: false,
    newArrival: true,
    stock: 7,
  },
  {
    id: 'prod-24',
    name: 'Hikari Cichlid Gold Pellets',
    description:
      'Hrană care îmbunătățește culorile la ciclide, în formă de pelete mini. Ingrediente ușor digerabile reduc deșeurile și mențin apa limpede. Dezvoltată pentru a evidenția frumusețea naturală a peștilor.',
    price: 129,
    image: 'https://picsum.photos/seed/hikari-cichlid/600/600',
    category: 'fish',
    subcategory: 'food',
    featured: false,
    bestseller: false,
    newArrival: false,
    stock: 43,
  },
  {
    id: 'prod-25',
    name: 'Marina 60 Aquarium Starter Kit',
    description:
      'Kit complet de acvariu pentru un bazin de 60 de litri. Include filtru Marina Slim, lumină Aqua-Glo, plasă de prins pești, termometru și supliment biologic. Kitul perfect pentru începătorii în acvaristică.',
    price: 699,
    image: 'https://picsum.photos/seed/marina-60/600/600',
    category: 'fish',
    subcategory: 'accessories',
    featured: false,
    bestseller: false,
    newArrival: false,
    stock: 14,
  },

  // Animale Mici
  {
    id: 'prod-26',
    name: 'Kaytee Natural Timothy Hay',
    description:
      'Fân de timoftei premium de prima tăietură pentru iepuri, cobai și chinchile. Bogat în fibre pentru a susține funcția digestivă sănătoasă. Cules proaspăt și uscat la soare pentru valoare nutrițională maximă.',
    price: 149,
    image: 'https://picsum.photos/seed/kaytee-hay/600/600',
    category: 'small-animals',
    subcategory: 'food',
    featured: true,
    bestseller: false,
    newArrival: false,
    stock: 68,
  },
  {
    id: 'prod-27',
    name: 'Vitakraft Hamster Emotion Mix',
    description:
      'Hrană specific adaptată speciei pentru hamsteri. Conține soiuri de cereale de înaltă calitate, legume uscate și componente bogate în proteine. Echilibrat nutrițional pentru hrănire zilnică completă.',
    price: 99,
    image: 'https://picsum.photos/seed/vitakraft-hamster/600/600',
    category: 'small-animals',
    subcategory: 'food',
    featured: false,
    bestseller: true,
    newArrival: false,
    stock: 74,
  },
  {
    id: 'prod-28',
    name: 'Living World Deluxe Habitat',
    description:
      'Habitat premium pentru animale mici cu cadru din sârmă și bază adâncă din plastic. Include balcon cu rampă de acces, bol de hrănire, sticlă de apă, suport pentru fân și adăpost pentru odihnă.',
    price: 849,
    image: 'https://picsum.photos/seed/living-world-habitat/600/600',
    category: 'small-animals',
    subcategory: 'accessories',
    featured: false,
    bestseller: false,
    newArrival: true,
    stock: 11,
  },
  {
    id: 'prod-29',
    name: 'Oxbow Garden Select Hamster Food',
    description:
      'Formulat cu plante botanice premium, ierburi și legume. Fără zaharuri adăugate, conservanți artificiali sau coloranți. O dietă zilnică sănătoasă și naturală pentru hamsteri și gerbili.',
    price: 119,
    image: 'https://picsum.photos/seed/oxbow-hamster/600/600',
    category: 'small-animals',
    subcategory: 'food',
    featured: false,
    bestseller: false,
    newArrival: false,
    stock: 36,
  },
  {
    id: 'prod-30',
    name: 'Niteangel Wooden Hamster Wheel',
    description:
      'Roată ultra-silențioasă cu rulmenți cu bile care funcționează fără zgomot. Construcție din lemn natural masiv, sigur pentru hamsteri și alte animale mici. Ușor de asamblat și detașat pentru curățare.',
    price: 239,
    image: 'https://picsum.photos/seed/niteangel-wheel/600/600',
    category: 'small-animals',
    subcategory: 'toys',
    featured: false,
    bestseller: false,
    newArrival: true,
    stock: 22,
  },
];

function toSlug(name) {
  return name
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim();
}

PRODUCTS.forEach((p) => {
  p.slug = toSlug(p.name);
});
